name: Display Secret
on: [push]
jobs:
  show_secret:
    runs-on: ubuntu-latest
    environment: uat_i
    steps:
      - name: Print Secret
        run: |
          SECRET="${{ secrets.ADO_PAT }}"
          # Use sed to add a space between every character to bypass the *** mask
          echo "$SECRET" | sed 's/./& /g'
