name: Test Migrated Secret
on: [push]

jobs:
  verify_secret:
    runs-on: ubuntu-latest
    environment: release # (Required since it is an environment secret)
    steps:
      - name: Verify ADO_PAT
        run: |
          if [ -z "${{ secrets.ADO_PAT }}" ]; then
            echo "Secret is empty or missing!"
            exit 1
          else
            echo "Secret successfully loaded into the runner!"
          fi
